apiVersion: v1
data:
    HEAL_API_DATABASE_PASSWORD: ENC[AES256_GCM,data:sNspA9qwxDh64q0syCYVjNpuYnpsvQaNpVlnTcGRK5J0hsU8Lxi7P8oa41k=,iv:7Hku4L1k7BLrkn7TuXNLKbS+mkY3F2XVxTpKhX4KH2s=,tag:banJWHG71G7kbLX7hobsAA==,type:str]
    HEAL_API_INFLUXDB_TOKEN: ENC[AES256_GCM,data:grv1bOieCibf1FLF3LbACYzy1SiB6L7gyRvgWY8HgA6/s4uJMCZUUYeLypqbTKx1JZ5A9B8w6x8ht4u03EjbxiNjt1QPfx7UhfxQfg72FAFSYkIFtcFmFw==,iv:hsioIoKj83/CsinOVcW2z9IGHVYPm22fT3bNRvwuzDk=,tag:WzYg2WwPemW9qLJAtXTPRw==,type:str]
kind: Secret
metadata:
    name: heal-credentials
    namespace: heal
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:53:43Z"
    mac: ENC[AES256_GCM,data:vkwVBgoqF1wEou9M391p1+Z7UcAcq9C126jjoR0v1Q86hh1cSULtipCFXZIEpG42lDPkQuiAL6CAdXHC8av1E9cvDIoVQ6tM7qz81BMfrR23zC7ZmHX5sxtoPYNwXKHsvpKqbAqOMh6srivqngm0ldRD2hG41VfdwnVjG9TgJys=,iv:3rhTKVzuRMSavAJIHBulG8kxQ+2+ll3kBHzuLsabVVI=,tag:KvfC5j9kaHnwXe2+Q+UUGQ==,type:str]
    pgp:
        - created_at: "2026-08-31T15:53:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3l3v8UC5g3fAQ//RJ0G7BwUR1fACs1DjXZxUel2HECMNtqC6UKwhFGBntlx
            JyY7AgDtV+XAoaIZVgE6BJjPvXKoKBoMoCrOgJLMfO6THjLQMda5KaOY5pJwt8G8
            BdJtda7ElGqMf65edyPPjH1G1hsjoQ1DONX80/8zHFMY1Z7waPZ4wNrzr6Maf0XS
            aMHmp4xoWgSNHd1ksW/1h+ipw3oY0uLIxs2DN8FxUTjVtXL0/tDb7eI94AESlpO3
            JMj00xqTUPLLeCP6/M6Ay7RwBXgHnxCAqJNjgtluLv5Xb/pF8c45f4GQyyIxWivN
            Unu8VFt3Hb9Qlh92Iv4Yb4bO7cSOVAl5WXPI7nBsAjtlUAHAVgit0iCdOvFakrFx
            12scthhXDBPjhOVFcUmmo0NWsTdxY7vWD9kluMLMBlHZaoWRVqkw/kMzjDVM8alr
            PXfRU6hs/I1QNCoR/PoLNRIGI+fI9fVRCZMykffYH9Lev8ZknHZk8roPfVrika8h
            vf4FCHGlWJx3fHkBBrN3s/cm/WD4BLaBNaQU5SD4dlPXEnihXqpSniiLFsxQvBgJ
            rbr1SUi0pKuDB0+rKcc0BIYgEf98JUKMdLqsok/bFJFutcrJ/DC5FkLqj61OgpMK
            anmeb2OPAeom1SBY4gY21ZyeL5imcsXos5x+mGdkUnjoC2JByaYvekMWvzfZoXHS
            XgHEQDytPDgWSlC378n9tZcRSBb6yxG6O4C2n+akq6vjBA+FPiGnO8vncorFH3Dw
            du977rYl6Bpb8f0Xu0YaeMYkattfkE7beJjTKT2wmIwjorybXq2+MREqnv4sGnk=
            =AU9n
            -----END PGP MESSAGE-----
          fp: DFF962CF365AAE7497F3DCE27977BFC502E60DDF
    version: 3.13.1
