apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:3D7R1nAJB/Y5YtgpoNcSulLoq0+7BnsJw/ffzVT+WOFSPB3IFp677YhVCG8=,iv:cmoCWRNW8DG/lYhIja0adDZ5UpqES6zwCGFr1WVwxQM=,tag:+s9BL7KOs8EDgU65KMz0Iw==,type:str]
    admin-token: ENC[AES256_GCM,data:Q2MMfZlLNpp2peFaovpXyYNhvmZlk1qrR/GN2NR8KDrmf+Jmi/DmfUadYIxsPdKbqoM4eQLXRNrIQfEY8cfFD6Fnch7emWqdjx2h+LFWOZ/sHWC+7oTRwg==,iv:M7Yv9HdDYqluRKdPG3QH9FImx/TUPfkCIrSv+Wz5/Gk=,tag:JXcQZ9bNPa9QtbcroilESg==,type:str]
kind: Secret
metadata:
    name: influxdb-credentials
    namespace: heal
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:53:43Z"
    mac: ENC[AES256_GCM,data:KmBjSFaDTxq8sjO0qnca/1qaajX/umxnKqm8cPk6XRNIWMH8FyHpgQqCDi3cz6dPWF5Ks2sUFGXrYBWw5Bie6gpT0QMkXFcbno8+ekXy1XyJuMB7YfpV3k3uC252CGDwQkOH1bdwwsA4F0MgY7OqoHVBeV6SxrS//nVGhmB8+nc=,iv:hWcwCDi/ag1PE1WPFLD56cjDTihWg1xoGmCCPEBoeP0=,tag:IE5JVP3GpwbM7Zj6dU3kkQ==,type:str]
    pgp:
        - created_at: "2026-08-31T15:53:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3l3v8UC5g3fAQ//YMeIo0JYNhEmAxuPGim8sFv2qqpHbWS0T5Jmf+JFX5WL
            W2EqjScYBsh07qaF8aJwPVlO7DWUrbQy4fHGXffTpUcBXfRY7o9j7boLc3KeoEvu
            dfXnSZSaD5Rdx6rNxmmdpUF1+rJvMz8d9gZCZHgnw8lJ1L/IcW9eE/cGuYW+JO2r
            +B7OfjgJndmZRk6HOF0OkKhwoM0fp7Ht3OHNnQ8vvKxMETk0pupw9RNvdoEipFND
            U1nC+ofEOjzE0vbwbD7FrRnzv65wADP2V+vDBPclL3tZ/DxHBJnPcSI1WiojcSHV
            ld/hdS9CFb9dDGTKoJbJb8T+fipi0pNrK3SZZMDewJd6YgdxRCxggiUCaZkFXdPd
            B/AUD6T3snrprpxWen/hIhxX52eQHuabqJiipBpSXCA/Y0O/vGZzD4vb8lEaOHDB
            mZVMT8+UITmG/wVW9/bu7+crX9pk4nklYQRo1u4CWClql9+jmQdUvxKTjrM5I108
            DSGmNFCmYGA71FG8i0j+bTi+2Pn3aEEP9kSRZ/RmMs+7eutn6gIAr1T2A7DTgUGE
            Kh8NZLm8FpGNfYZIcTXUiURR0/P36DZfEzJ1dsseNaXgiTId8E9lj1qb2uQQUKa+
            UpHRTKTK8a1EiaoXtf2nSW0wc4gNLQBs7HIjBinTgFt9gGJt6/NM7/WpmKJJjRDS
            XgEdSUUWp5862/fC6xHLtDCxJvzARrY/ruamdqIdtE9KJaEswgON0OvqldIYhB1o
            YJyacJbylLbQE89VANnMtiCWAXZWy5kWsRXKQBO55udiTAWmj89IM5uwDhqTjb4=
            =1qlf
            -----END PGP MESSAGE-----
          fp: DFF962CF365AAE7497F3DCE27977BFC502E60DDF
    version: 3.13.1
