apiVersion: v1
data:
    mysql-password: ENC[AES256_GCM,data:I1hWmp252phEkgwo6oa0d8m3TZc8l7F84yFE22ZTRWJs0/isgrgUU8QCbhE=,iv:ESsqWzrcsiCp5LLNxGVwthqc3XFgAloJAAlCHHipblY=,tag:S9XhPVkHYNibGeCZPPUhOg==,type:str]
    mysql-replication-password: ENC[AES256_GCM,data:oYsghyiE9B2qKS3sDta9Y1ixeQMRotUpEs3Y4l0VAd3yK+Jxo5Biml2e0tw=,iv:+pgB2d0L+KMXkyhKw6Wga5U7qkaXJa0eCXiJEGdO+Cs=,tag:OK6DNpReMtQSG8rWH7JLnQ==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:TFHWQEfdtl4O/Oo2WRzgzPtzIwk2G7vz3mJTtA/sqxYZ3JReSmo+0OpoBUg=,iv:Wn4Ln/BweTbSsgCdckPtd0jQGAeekdRXqhDGjPRUJso=,tag:ipKRp4DqB/tvPesZTJZW+w==,type:str]
kind: Secret
metadata:
    name: mysql-credentials
    namespace: heal
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:53:43Z"
    mac: ENC[AES256_GCM,data:ZWGOR9y4R4yQxcnRlae4j7ZglbOvufNJIj3uWGDwe45cyEjB4ZnplgEq6vH6soLqfXwoLWWPSgRNa7ggZrWGKuWhDlr3dVcxlN49kbNcrUzaO779eF9StNBKbYCihFnDsJZEJ7e/7Ovm7G0g5OrbAiIx/eLzoEH7NuXVq+QlaCU=,iv:ZlGfzLQDyalQtXXb8Q/wM0pfsSBXhMDEqpHTBSaa4Wo=,tag:UPJQkeo/RbTciv3EJ2GAYw==,type:str]
    pgp:
        - created_at: "2026-08-31T15:53:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3l3v8UC5g3fAQ//ZDBwotHhJ/W/JjjgW0EjJTbwyZTnLzF8w22vOguCXP2k
            IUXew3p9dDvnlEfp1qa0D4c1fbCA+FmdvrklmhLvaLC+HyQ4cmtsSRdOemiw6tDG
            vRmhjiAeiIAn+DISnbdNb1waO0GF3qChLs7iTGCyLmRbcr/QIxvk3atgzDD7pCfJ
            VKvGSchHXvk30rRpCLoCACjUh7ROdRbDGDtpq6tgkdNjYJwJVFDkGujtwa0hFpC/
            2POXQtS4+Ju3uGN4AeZPyELy8ov27SXIKHCBbtGJeOq3D8Q3zqRwTObLX9gcHTkv
            2Ty0bzhgMiNbGqmSn4iOqEa9Ih7XzMmsAZeXFygbvfcLQAQKnm7mYVnu51hq0VBv
            nZ7/C/LgBPQu+UYNeKcXpKAbsfZTRLDXummN61m4Z/ctguWhCak35HXvainq86G8
            SbjfNVHJ0wN/fzepoS1SxtpMrm/s12r3Nap63NvXcBjXT8DGQ5qGIIxcPN5pQod2
            EGPRbrH57rKFEYEJH1w3565KwNj1T6r5KkNbgmrop9Bd9XL+Ag0pHFreEgbDOIKg
            +8YqcF5DVzoQ99YFkIXuz/I/hUbm5u7NdCb3hr4LYxukJOxADIuxgsd8IWRjldDQ
            GCE2HlZx5MRlQnXIBvw0JWyoEJDs2URadeL9JnFWBcGjfZkI/G3M1c+5CB0O2fLS
            XgFI6u73VDLSLKaC1A0w9p7Ulae3+B02OZavwDp5bnRRciUGwYGG/SqagXHc3q6F
            0vZGH79uIm+BwSS3CX+1ZzgivU775VcuA5hhsDvj9f4zZagq6O5hlEL23KhURNA=
            =k9WF
            -----END PGP MESSAGE-----
          fp: DFF962CF365AAE7497F3DCE27977BFC502E60DDF
    version: 3.13.1
