apiVersion: v1
data:
    HEAL_API_DATABASE_PASSWORD: ENC[AES256_GCM,data:ddjifKhI2h5AFyAW+49iG3eHK8ToJC3dvwbzFgLiznI/2kSaQu1rRMMiQKQ=,iv:iLCMMfkFkAOJgNGDCxgT+0a94yrfrUtJTC+crAwNH4g=,tag:wKSzCR8O6d327CqQAzXQsA==,type:str]
    HEAL_API_INFLUXDB_TOKEN: ENC[AES256_GCM,data:pWId1vQU4XN9g4JrruIkpy5mDSHij+ujpH/oeOtHfx/EtJq9xXdP2EWomF6ygcS1e0cSqf2wUJt/ViDlLlqW1I0KnWgxvtRJem4wwawFLqp2sfjC6+T6UQ==,iv:Knvvv3h5otNFYcjRD8l/izyP6XNTveaSiQpXi3d7Cww=,tag:BYcHy9iosUGbxWXiBKT56g==,type:str]
kind: Secret
metadata:
    name: heal-credentials
    namespace: heal
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:53:44Z"
    mac: ENC[AES256_GCM,data:JS+YgXqoHsjYcS/aV99A44yJgL5PEdZWr9V2qA3yjQaO4igYmOGYRKwWMsBy8jWoXiNSxKRRESOC1hco1v3//B3JOG4qr7E9ofnCyDfwrEpV00mAyCVXmeSQx2lRNlEXiOXBR+hBnSoZcgumqNLWVQZx0iujFD95YK8y/qlpmf8=,iv:GALf6DdFZ1zy0L7vFbFHhzVBn+F99+yz7tSAzXu7VDA=,tag:0D9yxAtRni6QyO1fC+J4+w==,type:str]
    pgp:
        - created_at: "2026-08-31T15:53:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxTpt9ET+Wh0ARAAitMK+fVuIRaPypD2sMZYg8QyfegHN7b9H7KcmPOxSfmZ
            AFLXinle8KfYbtk3wc5gv/VIpfNN2zqGFxgoy2JTMB0lQoCCzcZ2XJ8IULB4xugt
            nBWZLYz+BCKUBGC4IFodb/C3NRP2o3Ifjng0EJilgW3oceO+AYub8h3C3TNlXsur
            wDoSFRwN3LJgiQRtAUEupRoOL4jpYpepOmrVL4WjZsCdRStChNJU5mYpl4WHK+Ol
            soe5HmGw7rKuCTg+PV7ZU1xM0tN0D6Ge1oyIBYzc7J06WWmR9eZySmNz1RhV9bcr
            XzOktGXOzRZ1CcQ51xHKxSxZUu3WEoUFuVl/6S+gx/goQUtQlLtIDt5Nk/q/1YTj
            lxoRaL0xtNsflk7i3UWyhqYj/WFvfTI6O2/JgfOC36DKFl/w4fZ8mPWGwo21xq2a
            pwWVosGSLBOpKic16YKdRuBO8rD7RDuB2pKd8pMsjk+XaMDst1ILNhRH0Fgo7jLA
            goWGz21DtwkLsQKV9+o5ZF9+JPUBIqd6oz3DD1pjB84YhIqi+L50VfD+3VHqC2RI
            p3KhC2vLM5YBK5I6JYucBD1LmWIJl0LvbIZv+kbPsiFpjKQe71dEgiZRSNR2Qifd
            WBkXJx50gb3wl+vTnRv3d8UpXKKrSUr5zJPa+EEmW5zleB6Y7OMuASMEqjahuLjS
            XgEofhO9flnbWe39LXOM7KjlJxXZHxwncyg3rpXiopDmOSLYWn9FOrnxGGkFYjbu
            Qh64lGu/CGPyOV1dGQN00f9epUIpI5dgVeUO6n/cyFsTyIg4ENcfTjQ/H4q4xq4=
            =gGLs
            -----END PGP MESSAGE-----
          fp: 4F242C5432025E721A0EFAC014E9B7D113F96874
    version: 3.13.1
