apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:5Y2TSgOaoSSF5Z9VVb2U3LQeK9XjMQZTLFUR13jbOpRUv9OpHMviitZwtBU=,iv:hIiCFI7OI9SRMAHPZodd8e4UFoP/mbEVtfugS7wkJHU=,tag:KJafD2K5BeCFOZ7l16s3UQ==,type:str]
    admin-token: ENC[AES256_GCM,data:GNNlpPSv+/jgKLE/1n+d/Y8dVXg2vlwahD8xxxOhPr4I5UzA8y94/YhfrchsoWINWxUl8+dEJcOwZ66IstDVxRCHB3nPvIr+fhiHnRFHcLmJyP8iwuK7+A==,iv:h2GVkyWHxoeCNmAx5I0hJq4Pb6fi9Ye2kApQngtDgZg=,tag:L34Z2HwaBUXNWuXkwBwugg==,type:str]
kind: Secret
metadata:
    name: influxdb-credentials
    namespace: heal
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:53:44Z"
    mac: ENC[AES256_GCM,data:H7FvQsCDF4UFwx74x6VYtFJpfmfLajljZhj2aRG4r8QEEHZoBcgRO0825oYeMg887AYgME+hhE5c1ncQwdTluqHZZqcdKk5lPlQMLuY0jsJk3Gh4zLjFPU10ZadctNpWlTX4CIFaSUXgX+0la+43yL1RqcmNBHhEPIKykttiwBE=,iv:5t9VTH3hz/Z0mB/ZnCiAYpTFZ5XKzzWl8DM/ITgRYgI=,tag:KkrfUDRHr7iDcyBWU3omiw==,type:str]
    pgp:
        - created_at: "2026-08-31T15:53:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxTpt9ET+Wh0AQ/+JnqVKwVKUsSPEfusixfbvtMFONhGmskI7FCLQLKVT2g0
            17ghKqJltjhCWPhgvPoaPNfE8dn6aWiOon7mz2fdrPal1osQryVWeqKw1fNZX8QI
            3nr5WOHh9lUtbdN83I/eb+s4FjDhVvHZZ9QS+a+A0ukBedz4Lsc1Eaiid0EijWD0
            UcrSkaZONo4nW3xFsySKOr0ONaNE3IAjDdVflyKWtb0YcozAe1NTJLQllblmkFTe
            foLT3I6Rb9weNyK4W6MJbUB7wFNRMuFUMvsV3dpZ/XmPW+/i9Aln9C0uL6zUgjPS
            7fMJwfPM4cv1Onc1xPBqtUZg9AnZubBf7V3DUijGnUg4GM9PJiO/Lj84KqHeTEDj
            3vLcu+dfU2U/doLe0u6pChEXWU8ec23bpDZRAiOXDtpl0Uv8sp1nAIuxzJGCUWBv
            qnaG0RHvNDaN8L+owN0C6KSNW1U8IQHlCHWCVswTsvQ5wXF0n1IKKs+sHG8nHrQM
            PZ1dV3YiNIND0Nd59DKpcZ7e5IFDWjfe/Cz3O4ryjwVg9ZlT7+/ZzjXxei3V6bUW
            jxHlw9mbIWiOTrggCuBqmoU0vaDe0lX6xFr4UVSQ8cAcjj6XIp35sFez7JDR4klN
            38OngB2A11eF+gzExIClW0QoimddKhQi6fxgMtEDQ5AITaCpvhM++Sr37V4NQZfS
            XgEo+Kmu2yt2hF2TkRmnbkYy6BjSL9tqay0n5zuFnv0cRvE6lFpYwxDsii3vjZwH
            LXUjUxbEfYL4bqrYX9xSt3fz1gdBm7TBuao6G6D0Pnff5a3jErQeGZTvqo18QaE=
            =4ZCO
            -----END PGP MESSAGE-----
          fp: 4F242C5432025E721A0EFAC014E9B7D113F96874
    version: 3.13.1
