apiVersion: v1
data:
    mysql-password: ENC[AES256_GCM,data:IApNPB9uuZJtvYwWfKPhpIK3A5SfeemZNGYp4rqSa4FRqog08sy4TBnE/Is=,iv:RvqHlWoi6K695+0gWrZRrNOPOSn62gI0fdBsmnvKHpI=,tag:CGs6xJ3j7pELoTQewH08LA==,type:str]
    mysql-replication-password: ENC[AES256_GCM,data:Kj2H/DRtQwPq09qpb67vyyEC47t3dwhieHc0+K+xvRuKuyq6lAxCk3WbkCQ=,iv:ZVTHa2Q/Dhf7F6kQze78vGk/dbM0/C8KAvA12OOzXrg=,tag:53KvTwBFMipPF58EwkDnBw==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:VUbTVKYcTdYc2tN7RihldNXKoXfSFwMtLxA+5FU8CSrPfK9ko65LzDdfn1Y=,iv:UbNwLAdKQKHhNdGAlGQoUP9UWwYBBYe/yBJ0GDumeno=,tag:iO3zr1O4AZo3pPs3Aafnbg==,type:str]
kind: Secret
metadata:
    name: mysql-credentials
    namespace: heal
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:53:44Z"
    mac: ENC[AES256_GCM,data:EQqqqegJUyHhQO9E/QKLZ86vdbq7BVF9BtHErqSAOUZAfijZZOwo2/JDy1aE9xGYk0F2BswrJhdxi/SViH7XlN80XaiwxLIjRThcVhv5F5v0BL5NoQnuC2YIHNI4F9+VZgq45MDy4emvzc6BcVR+gWDxQRPxYrKeE16LGJOaryk=,iv:VURGoLv3WyCwQq4j5SqYPAZlae+3Lvdr56Qud1hBtWU=,tag:OsjfVesjwKNW2krmiS2n5g==,type:str]
    pgp:
        - created_at: "2026-08-31T15:53:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxTpt9ET+Wh0AQ//RR7vvarM9sknn6xncUnEiS9vsPB/VZGFrxc1i4S2ePcC
            b0Z2nbc5CKWnJu6OKQUd59B+abBRUroER+h3t1C3/xyBwqFM399QN8IF8tY7EUNu
            AaBaWKdci6L9+Yn6nPGOcnaLjR49M2LFBHPRTBB2WRPu1Jw3evBiEbUlysfsr4cO
            dGf/lRPNUlee8OlWgLf0GyMA859aEXg1uob5o6KjULqGZaB7Hj0+DeKgZaC/8O3a
            JFZkPB98kTBkQXy5bYEoEuhjj+MdLiIV/5X+wbX/IkhVpWlw6EUv0w/pSfOV3p8p
            5pO/pzRC+pqEfPVy5da7TesrGeRkOvYVf5BJ1gC3U8fz1X+xdqs0fDa/LgSb+UO8
            0RkME/KH0efeBqlCiBBEw2KoyxdUqgdRxmLMevaPVzquL5p+SkbiJt9tEN/9c1R3
            /yC55kiUMghNQZ+ianKqnMP9CsC64CJj+aoOnEPoDT4GWtj+sef+qj663187fsYZ
            C5+tx+aeCLp7FuJPJFFAD0M4nGmLBuv6vOP3ipiuR/jWVqRmtTM4HoZf3Yxq8e55
            DUhvsjjgXqs0zzFn5dF6mHJvYqZvcHmvKV4/Yiug3oaj/3y6PfW/oMFtBpErmILM
            Pn/2VuUFR3KrLB3l+ChNMsJ/LruJX+rf+K05h8hF4NxZvCiYUwBVihRyvdhZUB3S
            XgEoBvL7M+d2Gw2hIq8xJEmz+BBe/nhc4UEiLpmE+64PyuMc6mi9doBzVuVSLPh2
            Q6x1/J8+EOGBA5V0KHz9uw7lVJFB8eUxszfdB/bbhRozt83hjuW+Qm65+ooZWtE=
            =zFrv
            -----END PGP MESSAGE-----
          fp: 4F242C5432025E721A0EFAC014E9B7D113F96874
    version: 3.13.1
